### ISSUE TITLE
remove docs/README from docs.labdao.com

### ISSUE THREAD

**Issue by NiklasTR** [labdao/docs#12]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/18559148/161501070-42bab54c-ecdd-4a80-86c5-6180f1b0998f.png">

**Comment by jlevers** [comment]
i set it up this way because we need some sort of docs homepage, and we don't currently have one. how do you want to handle that? we could loop lily in to design something maybe

**Comment by jlevers** [comment]
pushing creation of a homepage for now -- update README itself.
