### ISSUE TITLE
Small molecule binding: how to use with your own data section

### ISSUE THREAD

**Issue by NiklasTR** [labdao/docs#138]

**Comment by mithrauki** [comment]
Hey, I'm not sure how to run it with your own data!

To do these docs, I need:

- A quick loom that covers the process step by step (starting from the end point of either Install Plex or Run an Example)
- Some example protein and ligand files and a suggestion for the place they'd most likely be kept on one's machine or elsewhere.

I'm envisaging something like this:

"So after successfully running an example, you now want to run equibind or diffdock with your own data.

Your data might be stored in X, Y, Z location(s).

[Optional] As you can see here, in X folder I have a bunch of different proteins and ligands. I want to dock protein A with ligand B.
[optional] If your data is in X, then first move it to....

If your data is in X, then write the following command in the command line.

For equibind, paste this command into the CLI:
For diffdock, paste this command into the CLI:

To see results, navigate to the folder [same as running an example]
To visualise results, use molstar [same as running an example]."

May also need options for running more than one protein or ligand at a time, but assuming that comes later after we've added parallelisation.

Any changes/improvements to this outline, please let me know.

@NiklasTR @thetechnocrat-dev @acashmoney 

Will need something similar for the protein folding tool too.

Thanks! :)

**Comment by NiklasTR** [comment]
this is a great outline. https://www.loom.com/share/b68b4983a78f496dae758796b6d1d941
