### ISSUE TITLE
creating a dedicated learn_more.md document for both labdao and openlab

### ISSUE THREAD

**Issue by NiklasTR** [labdao/docs#15]

**Comment by jlevers** [comment]
@NiklasTR you can now do this by creating a file called `learn_more.md` in `docs/labdao/` and `docs/openlab/`. you will need to put some front matter at the beginning, like this:

```md
---
title: Learn more
description: Learn more about LabDAO.`
sidebar_position: <x>
---
```

for a real-world example of front matter in action, check out [this file](https://raw.githubusercontent.com/labdao/docs/main/docs/labdao/mission.md) (it's easier to see the front matter in the raw file).

**Comment by NiklasTR** [comment]
amazing - thank you Jesse, the docs look great
