### ISSUE TITLE
upgrade docs to use tool instead of app in docs

### ISSUE THREAD

**Issue by acashmoney** [labdao/docs#169]
```[tasklist]
### Tasks
- [x] Update -app flag to -tool flag [bb813f6074faa7f47faea03bab0b998f26353d65](https://github.com/labdao/docs/commit/c488132b5b21065ba93085421ae0613437dd2296)
- [x] Update screenshots to use -tool flag (pending https://github.com/orgs/labdao/projects/17/views/1?pane=issue&itemId=24670010)
```

**Comment by acashmoney** [comment]
@NiklasTR since we reference using Colabfold in the Protein Folding section, I think we should reprioritize the Colabfold tool config prior to v0.6.0 release. Alternatively, we could hide the entire Protein Folding section, but I don't think this would is ideal

**Comment by NiklasTR** [comment]
closing as complete
