### ISSUE TITLE
enable mermaid based graphs for docs

### ISSUE THREAD

**Issue by NiklasTR** [labdao/docs#29]
Problem: Mermaid is a graph plotting tool in markdown that enables fast and easy generation of flowcharts of dependencies. This has value for application docs. Mermaid is not available in docusaurus. 

Proposed Solution: To include mermaid to docusaurus, an actively maintained project exists: https://github.com/sjwall/mdx-mermaid

I propose we integrate mermaid support.

**Comment by jlevers** [comment]
@NiklasTR the `main` branch settings were changed such that I can't merge the changes until they're reviewed -- would you mind taking a look at the PR?
