### ISSUE TITLE
share the zoom recording from our workshop in a Notion base

### ISSUE THREAD

**Issue by mithrauki** [labdao/docs#55]
Link is here: https://www.notion.so/labdao/Competitor-tools-d9954fd05e7842379cb2d0bb7e807704

Direct link to grain with transcript: https://grain.com/share/recording/7dc5b630-54d0-4544-bc2f-66da103a9cbb/Nx7ELZ747Dj36qizwgbZ87zoQu6qva5gIOCImXa0

Let me know if you can't access it

**Comment by NiklasTR** [comment]
Thank you!
